import type { ItemDef } from "./types";
import { getLocale } from "./i18n";

/**
 * Original item catalog. Names and stats are original to this project.
 */
export const ITEMS: Record<string, ItemDef> = {
  /* ---------------- Weapons ---------------- */
  weapon_iron_sword: {
    id: "weapon_iron_sword",
    name: "Iron Sword",
    kind: "weapon",
    rarity: "common",
    icon: "⚔",
    stack: 1,
    description: "A reliable iron blade for new warriors.",
    equip: { slot: "weapon", bonus: { attack: 6 } },
    classRestriction: ["warrior", "rogue"],
  },
  weapon_dagger: {
    id: "weapon_dagger",
    name: "Steel Dagger",
    kind: "weapon",
    rarity: "common",
    icon: "🗡",
    stack: 1,
    description: "A swift steel dagger, favored by rogues.",
    equip: { slot: "weapon", bonus: { attack: 5, attackSpeed: -0.15 } },
    classRestriction: ["rogue", "warrior"],
  },
  weapon_oak_staff: {
    id: "weapon_oak_staff",
    name: "Oak Staff",
    kind: "weapon",
    rarity: "common",
    icon: "✦",
    stack: 1,
    description: "A staff carved from oak. Channels mana.",
    equip: { slot: "weapon", bonus: { attack: 3, mpMax: 20 } },
    classRestriction: ["mage"],
  },
  weapon_steel_axe: {
    id: "weapon_steel_axe",
    name: "Steel Battleaxe",
    kind: "weapon",
    rarity: "uncommon",
    icon: "🪓",
    stack: 1,
    description: "A heavy two-handed axe forged of steel.",
    equip: {
      slot: "weapon",
      bonus: { attack: 12, attackSpeed: 0.15, defense: -1 },
    },
    levelReq: 5,
    classRestriction: ["warrior"],
  },
  weapon_runic_staff: {
    id: "weapon_runic_staff",
    name: "Runic Staff",
    kind: "weapon",
    rarity: "rare",
    icon: "✺",
    stack: 1,
    description: "A staff inscribed with arcane runes.",
    equip: {
      slot: "weapon",
      bonus: { attack: 14, mpMax: 60, attackRange: 2 },
    },
    levelReq: 12,
    classRestriction: ["mage"],
  },
  weapon_shadow_blade: {
    id: "weapon_shadow_blade",
    name: "Shadow Blade",
    kind: "weapon",
    rarity: "rare",
    icon: "✸",
    stack: 1,
    description: "A blade that drinks the light around it.",
    equip: {
      slot: "weapon",
      bonus: { attack: 18, attackSpeed: -0.2 },
    },
    levelReq: 12,
    classRestriction: ["rogue"],
  },
  weapon_titan_greatsword: {
    id: "weapon_titan_greatsword",
    name: "Titan Greatsword",
    kind: "weapon",
    rarity: "epic",
    icon: "⚔",
    stack: 1,
    description: "A massive blade said to have slain a giant.",
    equip: { slot: "weapon", bonus: { attack: 28, defense: 4, hpMax: 30 } },
    levelReq: 20,
    classRestriction: ["warrior"],
  },

  /* ---------------- Armor ---------------- */
  armor_leather_vest: {
    id: "armor_leather_vest",
    name: "Leather Vest",
    kind: "armor",
    rarity: "common",
    icon: "🧥",
    stack: 1,
    description: "Boiled leather. Light protection.",
    equip: { slot: "armor", bonus: { defense: 3, hpMax: 20 } },
  },
  armor_chainmail: {
    id: "armor_chainmail",
    name: "Chainmail",
    kind: "armor",
    rarity: "uncommon",
    icon: "🛡",
    stack: 1,
    description: "Interlocked iron rings.",
    equip: { slot: "armor", bonus: { defense: 8, hpMax: 50 } },
    levelReq: 5,
  },
  armor_plate: {
    id: "armor_plate",
    name: "Plate Armor",
    kind: "armor",
    rarity: "rare",
    icon: "🛡",
    stack: 1,
    description: "Heavy plate. Best for front-line warriors.",
    equip: { slot: "armor", bonus: { defense: 16, hpMax: 100, attackSpeed: 0.1 } },
    levelReq: 12,
  },
  armor_robe: {
    id: "armor_robe",
    name: "Mage Robe",
    kind: "armor",
    rarity: "uncommon",
    icon: "👘",
    stack: 1,
    description: "Embroidered robes that channel mana.",
    equip: { slot: "armor", bonus: { defense: 4, mpMax: 60 } },
    classRestriction: ["mage"],
  },

  helmet_iron_cap: {
    id: "helmet_iron_cap",
    name: "Iron Cap",
    kind: "helmet",
    rarity: "common",
    icon: "⛑",
    stack: 1,
    description: "Beaten iron headgear.",
    equip: { slot: "helmet", bonus: { defense: 2, hpMax: 15 } },
  },
  helmet_great_helm: {
    id: "helmet_great_helm",
    name: "Great Helm",
    kind: "helmet",
    rarity: "rare",
    icon: "⛑",
    stack: 1,
    description: "A full-faced helm.",
    equip: { slot: "helmet", bonus: { defense: 6, hpMax: 40 } },
    levelReq: 10,
  },

  gloves_leather: {
    id: "gloves_leather",
    name: "Leather Gloves",
    kind: "gloves",
    rarity: "common",
    icon: "🧤",
    stack: 1,
    description: "Simple leather gloves.",
    equip: { slot: "gloves", bonus: { defense: 1, attackSpeed: -0.05 } },
  },
  gloves_gauntlets: {
    id: "gloves_gauntlets",
    name: "Steel Gauntlets",
    kind: "gloves",
    rarity: "uncommon",
    icon: "🧤",
    stack: 1,
    description: "Forged gauntlets for melee fighters.",
    equip: { slot: "gloves", bonus: { defense: 3, attack: 2 } },
  },

  boots_leather: {
    id: "boots_leather",
    name: "Leather Boots",
    kind: "boots",
    rarity: "common",
    icon: "🥾",
    stack: 1,
    description: "Sturdy leather boots.",
    equip: { slot: "boots", bonus: { defense: 1, hpMax: 10 } },
  },
  boots_greaves: {
    id: "boots_greaves",
    name: "Steel Greaves",
    kind: "boots",
    rarity: "uncommon",
    icon: "🥾",
    stack: 1,
    description: "Iron-banded greaves.",
    equip: { slot: "boots", bonus: { defense: 4, hpMax: 30 } },
  },

  ring_strength: {
    id: "ring_strength",
    name: "Ring of Strength",
    kind: "ring",
    rarity: "uncommon",
    icon: "○",
    stack: 1,
    description: "A simple band that bolsters might.",
    equip: { slot: "ring", bonus: { attack: 4 } },
  },
  ring_mana: {
    id: "ring_mana",
    name: "Ring of Mana",
    kind: "ring",
    rarity: "uncommon",
    icon: "◯",
    stack: 1,
    description: "A circlet humming with arcane essence.",
    equip: { slot: "ring", bonus: { mpMax: 35 } },
  },
  ring_vitality: {
    id: "ring_vitality",
    name: "Ring of Vitality",
    kind: "ring",
    rarity: "rare",
    icon: "❍",
    stack: 1,
    description: "A ring that strengthens the bearer's life.",
    equip: { slot: "ring", bonus: { hpMax: 60 } },
  },

  amulet_warding: {
    id: "amulet_warding",
    name: "Amulet of Warding",
    kind: "amulet",
    rarity: "uncommon",
    icon: "◇",
    stack: 1,
    description: "Wards off some incoming damage.",
    equip: { slot: "amulet", bonus: { defense: 3, hpMax: 20 } },
  },
  amulet_focus: {
    id: "amulet_focus",
    name: "Amulet of Focus",
    kind: "amulet",
    rarity: "rare",
    icon: "◆",
    stack: 1,
    description: "Sharpens the wearer's focus.",
    equip: { slot: "amulet", bonus: { mpMax: 40, attack: 4 } },
  },

  /* ---------------- Materials (drops) ---------------- */
  mat_goblin_ear: {
    id: "mat_goblin_ear",
    name: "Goblin Ear",
    kind: "material",
    rarity: "common",
    icon: "♦",
    stack: 99,
    description: "Proof of a goblin slain. Some merchants pay for these.",
  },
  mat_wolf_pelt: {
    id: "mat_wolf_pelt",
    name: "Wolf Pelt",
    kind: "material",
    rarity: "common",
    icon: "♣",
    stack: 99,
    description: "A coarse wolf pelt, useful for armor crafting.",
  },
  mat_orc_tusk: {
    id: "mat_orc_tusk",
    name: "Orc Tusk",
    kind: "material",
    rarity: "uncommon",
    icon: "♠",
    stack: 99,
    description: "A heavy tusk taken from a fallen orc warrior.",
  },
  mat_iron_ingot: {
    id: "mat_iron_ingot",
    name: "Iron Ingot",
    kind: "material",
    rarity: "common",
    icon: "▮",
    stack: 99,
    description: "A bar of forged iron.",
  },
  mat_steel_ingot: {
    id: "mat_steel_ingot",
    name: "Steel Ingot",
    kind: "material",
    rarity: "uncommon",
    icon: "▰",
    stack: 99,
    description: "Refined steel suitable for fine weapons.",
  },
  mat_arcane_dust: {
    id: "mat_arcane_dust",
    name: "Arcane Dust",
    kind: "material",
    rarity: "uncommon",
    icon: "✧",
    stack: 99,
    description: "Dust shed by magical creatures.",
  },
  mat_shadow_essence: {
    id: "mat_shadow_essence",
    name: "Shadow Essence",
    kind: "material",
    rarity: "rare",
    icon: "✤",
    stack: 99,
    description: "Bottled twilight, resonant with darkness.",
  },
  mat_dragon_scale: {
    id: "mat_dragon_scale",
    name: "Dragon Scale",
    kind: "material",
    rarity: "epic",
    icon: "✥",
    stack: 99,
    description: "A glittering scale shed by an ancient drake.",
  },
  mat_wood_log: {
    id: "mat_wood_log",
    name: "Wood Log",
    kind: "material",
    rarity: "common",
    icon: "▭",
    stack: 99,
    description: "A length of timber.",
  },
  mat_stone_block: {
    id: "mat_stone_block",
    name: "Stone Block",
    kind: "material",
    rarity: "common",
    icon: "▪",
    stack: 99,
    description: "A blocky chunk of stone for building.",
  },

  /* ---------------- Consumables ---------------- */
  pot_minor_heal: {
    id: "pot_minor_heal",
    name: "Minor Health Potion",
    kind: "consumable",
    rarity: "common",
    icon: "❤",
    stack: 99,
    description: "Restores 60 HP.",
    consume: { healHp: 60 },
  },
  pot_minor_mana: {
    id: "pot_minor_mana",
    name: "Minor Mana Potion",
    kind: "consumable",
    rarity: "common",
    icon: "✦",
    stack: 99,
    description: "Restores 40 MP.",
    consume: { healMp: 40 },
  },
  pot_greater_heal: {
    id: "pot_greater_heal",
    name: "Greater Health Potion",
    kind: "consumable",
    rarity: "uncommon",
    icon: "❤",
    stack: 99,
    description: "Restores 180 HP.",
    consume: { healHp: 180 },
  },

  /* ---------------- Combat Charges (consumable buffs) ---------------- */
  charge_spirit: {
    id: "charge_spirit",
    name: "Spirit Charge",
    kind: "consumable",
    rarity: "uncommon",
    icon: "⚡",
    stack: 999,
    description:
      "Empowers your physical attacks for 30 seconds. (+50% melee damage)",
    consume: {},
  },
  charge_mana: {
    id: "charge_mana",
    name: "Mana Charge",
    kind: "consumable",
    rarity: "uncommon",
    icon: "✨",
    stack: 999,
    description:
      "Empowers your magic attacks for 30 seconds. (+50% spell damage)",
    consume: {},
  },

  /* ---------------- Crafting chain (ore -> ingot -> part -> weapon) ---------------- */
  mat_iron_ore: {
    id: "mat_iron_ore",
    name: "Iron Ore",
    kind: "material",
    rarity: "common",
    icon: "▱",
    stack: 99,
    description: "A chunk of raw iron ore. Smelted into iron ingots.",
  },
  mat_coal: {
    id: "mat_coal",
    name: "Coal",
    kind: "material",
    rarity: "common",
    icon: "▩",
    stack: 99,
    description: "Black fuel rock. Required for smelting steel.",
  },
  mat_gold_ore: {
    id: "mat_gold_ore",
    name: "Gold Ore",
    kind: "material",
    rarity: "uncommon",
    icon: "▦",
    stack: 99,
    description: "Glittering ore.",
  },
  mat_gold_ingot: {
    id: "mat_gold_ingot",
    name: "Gold Ingot",
    kind: "material",
    rarity: "uncommon",
    icon: "▰",
    stack: 99,
    description: "Refined gold for fine jewelry and inlay.",
  },
  part_iron_blade: {
    id: "part_iron_blade",
    name: "Iron Blade",
    kind: "material",
    rarity: "common",
    icon: "⫶",
    stack: 99,
    description: "A finished iron blade, ready to be hafted.",
  },
  part_steel_blade: {
    id: "part_steel_blade",
    name: "Steel Blade",
    kind: "material",
    rarity: "uncommon",
    icon: "⫷",
    stack: 99,
    description: "A finely-tempered steel blade.",
  },
  part_hilt_wood: {
    id: "part_hilt_wood",
    name: "Wooden Hilt",
    kind: "material",
    rarity: "common",
    icon: "▤",
    stack: 99,
    description: "A wrapped wooden hilt for a sword or dagger.",
  },
  part_hilt_steel: {
    id: "part_hilt_steel",
    name: "Steel Hilt",
    kind: "material",
    rarity: "uncommon",
    icon: "▥",
    stack: 99,
    description: "A reinforced steel hilt.",
  },
  part_staff_core: {
    id: "part_staff_core",
    name: "Runestone Core",
    kind: "material",
    rarity: "uncommon",
    icon: "❖",
    stack: 99,
    description: "A runestone that focuses the staff's mana flow.",
  },
  part_axe_head: {
    id: "part_axe_head",
    name: "Steel Axe Head",
    kind: "material",
    rarity: "uncommon",
    icon: "▶",
    stack: 99,
    description: "A heavy steel axe head, ready to be mounted.",
  },

  /* ---------------- Lootboxes (consumable items) ---------------- */
  lootbox_common: {
    id: "lootbox_common",
    name: "Wooden Cache",
    kind: "lootbox",
    rarity: "common",
    icon: "▣",
    stack: 99,
    description: "A modest cache. Common items.",
    lootboxId: "lootbox_common",
  },
  lootbox_rare: {
    id: "lootbox_rare",
    name: "Iron Cache",
    kind: "lootbox",
    rarity: "rare",
    icon: "▥",
    stack: 99,
    description: "A reinforced cache. Often contains rare gear.",
    lootboxId: "lootbox_rare",
  },
  lootbox_epic: {
    id: "lootbox_epic",
    name: "Gilded Cache",
    kind: "lootbox",
    rarity: "epic",
    icon: "▦",
    stack: 99,
    description: "A gilded cache reserved for heroes. Epic loot inside.",
    lootboxId: "lootbox_epic",
  },
};

export const ITEM_LIST: ItemDef[] = Object.values(ITEMS);

export function getItem(id: string): ItemDef | null {
  return ITEMS[id] ?? null;
}

export function rarityColor(r: string): string {
  switch (r) {
    case "common":
      return "#cfcfcf";
    case "uncommon":
      return "#7be07b";
    case "rare":
      return "#7aa6ff";
    case "epic":
      return "#d986ff";
    default:
      return "#ffffff";
  }
}

const RU_NAME: Record<string, string> = {
  weapon_iron_sword: "Железный меч",
  weapon_dagger: "Стальной кинжал",
  weapon_oak_staff: "Дубовый посох",
  weapon_steel_axe: "Стальная секира",
  weapon_runic_staff: "Рунический посох",
  weapon_shadow_blade: "Клинок Теней",
  weapon_titan_greatsword: "Двуручник Титанов",
  armor_leather_vest: "Кожаный жилет",
  armor_chainmail: "Кольчуга",
  armor_plate: "Латные доспехи",
  armor_robe: "Мантия мага",
  helmet_iron_cap: "Железный шлем",
  helmet_great_helm: "Большой шлем",
  gloves_leather: "Кожаные перчатки",
  gloves_gauntlets: "Стальные рукавицы",
  boots_leather: "Кожаные сапоги",
  boots_greaves: "Стальные поножи",
  ring_strength: "Кольцо силы",
  ring_mana: "Кольцо маны",
  ring_vitality: "Кольцо жизни",
  amulet_warding: "Амулет защиты",
  amulet_focus: "Амулет сосредоточения",
  mat_goblin_ear: "Ухо гоблина",
  mat_wolf_pelt: "Волчья шкура",
  mat_orc_tusk: "Клык орка",
  mat_iron_ingot: "Железный слиток",
  mat_steel_ingot: "Стальной слиток",
  mat_arcane_dust: "Магическая пыль",
  mat_shadow_essence: "Эссенция тьмы",
  mat_dragon_scale: "Чешуя дракона",
  mat_wood_log: "Бревно",
  mat_stone_block: "Каменный блок",
  pot_minor_heal: "Малое зелье лечения",
  pot_minor_mana: "Малое зелье маны",
  pot_greater_heal: "Большое зелье лечения",
  charge_spirit: "Заряд духа",
  charge_mana: "Заряд маны",
  mat_iron_ore: "Железная руда",
  mat_coal: "Уголь",
  mat_gold_ore: "Золотая руда",
  mat_gold_ingot: "Золотой слиток",
  part_iron_blade: "Железный клинок",
  part_steel_blade: "Стальной клинок",
  part_hilt_wood: "Деревянная рукоять",
  part_hilt_steel: "Стальная рукоять",
  part_staff_core: "Сердечник посоха",
  part_axe_head: "Топорище",
  lootbox_common: "Простой сундук",
  lootbox_rare: "Железный сундук",
  lootbox_epic: "Золочёный сундук",
};

const RU_DESC: Record<string, string> = {
  weapon_iron_sword: "Надёжный железный клинок для новичков.",
  weapon_dagger: "Быстрый стальной кинжал — выбор разбойника.",
  weapon_oak_staff: "Посох из дуба. Проводит ману.",
  weapon_steel_axe: "Тяжёлая двуручная секира из стали.",
  weapon_runic_staff: "Посох с магическими рунами.",
  weapon_shadow_blade: "Клинок, поглощающий свет.",
  weapon_titan_greatsword: "Огромный меч, сразивший великана.",
  armor_leather_vest: "Варёная кожа. Лёгкая защита.",
  armor_chainmail: "Сцепленные железные кольца.",
  armor_plate: "Тяжёлая броня. Лучшая для танков.",
  armor_robe: "Расшитая мантия, проводящая ману.",
  helmet_iron_cap: "Кованый железный шлем.",
  helmet_great_helm: "Полнолицевой шлем.",
  gloves_leather: "Простые кожаные перчатки.",
  gloves_gauntlets: "Кованые рукавицы для бойцов.",
  boots_leather: "Прочные кожаные сапоги.",
  boots_greaves: "Поножи, окованные железом.",
  ring_strength: "Кольцо, прибавляющее мощь.",
  ring_mana: "Обруч, гудящий магией.",
  ring_vitality: "Кольцо, укрепляющее жизнь.",
  amulet_warding: "Отводит часть урона.",
  amulet_focus: "Заостряет сосредоточение.",
  mat_goblin_ear: "Доказательство убитого гоблина.",
  mat_wolf_pelt: "Грубая волчья шкура для брони.",
  mat_orc_tusk: "Тяжёлый клык павшего орка.",
  mat_iron_ingot: "Брусок кованого железа.",
  mat_steel_ingot: "Сталь для тонкого оружия.",
  mat_arcane_dust: "Пыль с магических существ.",
  mat_shadow_essence: "Бутылка сумерек.",
  mat_dragon_scale: "Сверкающая чешуя древнего дракона.",
  mat_wood_log: "Кусок древесины.",
  mat_stone_block: "Каменный блок для стройки.",
  pot_minor_heal: "Восстанавливает 60 HP.",
  pot_minor_mana: "Восстанавливает 40 MP.",
  pot_greater_heal: "Восстанавливает 180 HP.",
  charge_spirit: "Усиливает физическую атаку 30 сек (+50%).",
  charge_mana: "Усиливает магическую атаку 30 сек (+50%).",
  mat_iron_ore: "Сырая железная руда. Плавится в слитки.",
  mat_coal: "Чёрный уголь. Нужен для выплавки стали.",
  mat_gold_ore: "Сверкающая руда.",
  mat_gold_ingot: "Очищенное золото для украшений.",
  part_iron_blade: "Готовый железный клинок.",
  part_steel_blade: "Закалённый стальной клинок.",
  part_hilt_wood: "Деревянная рукоять.",
  part_hilt_steel: "Усиленная стальная рукоять.",
  part_staff_core: "Рунический сердечник посоха.",
  part_axe_head: "Тяжёлый стальной обух.",
  lootbox_common: "Простой сундук с обычными предметами.",
  lootbox_rare: "Усиленный сундук с редким лутом.",
  lootbox_epic: "Золочёный сундук для героев.",
};

export function getItemName(def: ItemDef): string {
  if (getLocale() === "ru") return RU_NAME[def.id] ?? def.name;
  return def.name;
}

export function getItemDesc(def: ItemDef): string {
  if (getLocale() === "ru") return RU_DESC[def.id] ?? def.description;
  return def.description;
}
